services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass@word1
      POSTGRES_DB: digital_banking_db
    ports:
      - "5442:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - spring-cloud

  # RabbitMQ message broker
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - spring-cloud

  discovery-service:
    build: ./discovery_service
    container_name: discovery-service
    ports:
      - "8761:8761"
    networks:
      - spring-cloud

  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8800:8000"
    depends_on:
      - discovery-service
    networks:
      - spring-cloud

  customer-service:
    build: ./customer_service
    container_name: customer-service
    ports:
      - "8802:9001"
    depends_on:
      - discovery-service
      - postgres-db
      - rabbitmq
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=digital_banking_db
      - DB_USER=postgres
      - DB_PASSWORD=pass@word1
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      - spring-cloud

  loan-service:
    build: ./loan_service
    container_name: loan-service
    ports:
      - "8803:9002"
    depends_on:
      - discovery-service
      - postgres-db
      - rabbitmq
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=digital_banking_db
      - DB_USER=postgres
      - DB_PASSWORD=pass@word1
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      - spring-cloud

networks:
  spring-cloud:
    driver: bridge

volumes:
  rabbitmq_data: