server:
  port: 9002

spring:
  application:
    name: loan-service
  r2dbc:
    #    url: r2dbc:postgresql://postgres-db}:${DB_PORT:5432}/lending_app_db
    url: r2dbc:postgresql://postgres-db:5432/digital_banking_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pass@word1}
    pool:
      initial-size: 5
      max-size: 20

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka