server:
  port: 9002

spring:
  application:
    name: loan-service
  r2dbc:
    url: r2dbc:postgresql://postgres-db:5432/digital_banking_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pass@word1}
    pool:
      initial-size: 5
      max-size: 20

banking:
  loan:
    min-fund-limit: 500
    min-amount: 1000
    max-amount: 10000

rabbitmq:
  host: ${SPRING_RABBITMQ_HOST:rabbitmq}
  port: ${SPRING_RABBITMQ_PORT:5672}
  username: ${SPRING_RABBITMQ_USERNAME:guest}
  password: ${SPRING_RABBITMQ_PASSWORD:guest}
  connection-timeout: 5000
  listener:
    simple:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 2
        max-interval: 10000
  queue: loan.account.queue
  exchange: loan.exchange
  routing-key: loan.account

core:
  banking:
    base-url: http://localhost:8081/api/v1/core

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka