server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**

        - id: loan-service
          uri: lb://loan-service
          predicates:
            - Path=/loans/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

