server:
  port: 9003

spring:
  application:
    name: account-service
  r2dbc:
    url: r2dbc:postgresql://postgres-db:5432/digital_banking_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:pass@word1}
    pool:
      initial-size: 5
      max-size: 20

rabbitmq:
  host: ${SPRING_RABBITMQ_HOST:rabbitmq}
  port: ${SPRING_RABBITMQ_PORT:5672}
  username: ${SPRING_RABBITMQ_USERNAME:guest}
  password: ${SPRING_RABBITMQ_PASSWORD:guest}
  connection-timeout: 5000
  listener:
    simple:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        multiplier: 2
        max-interval: 10000
  loan:
    queue: loan.account.queue
    exchange: loan.exchange
    routing-key: loan.account
  account:
    queue: account.queue
    exchange: account.exchange
    routing-key: account.key

banking:
  account:
    currency: KES

eureka:
  instance:
    hostname: account-service  # Use container name
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka